-- 1. Orders Table (Pedidos)
drop table if exists orders;

create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Informações do Pedido
  order_number text unique not null,
  order_status text not null, -- Agendado, Completo, etc
  order_final_price numeric,
  order_quantity integer,
  date_order timestamp with time zone,
  date_delivery timestamp with time zone,
  
  -- Informações do Cliente
  client_name text,
  client_email text,
  client_document text,
  client_phone text,
  
  -- Endereço
  client_zip_code text,
  client_address text,
  client_address_number text,
  client_address_district text,
  client_address_city text,
  client_address_state text,
  client_address_comp text,
  
  -- Produto (Simplificado para o Principal)
  product_name text,
  product_code text,
  
  -- Financeiro / Usuários
  commission numeric,
  producer_commission numeric,
  logistic_operator text,
  delivery_man text,
  
  -- App Specific Extensions (Required for Dashboard/COD features)
  payment_status text default 'Pending', -- 'Pending', 'Collected', 'Remitted', 'Failed'
  cod_amount numeric(10,2) default 0,
  notes text
);

-- 2. Expenses Table (Financeiro)
drop table if exists expenses;

create table expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  description text not null,
  amount numeric(10,2) not null,
  date timestamp with time zone not null,
  category text,
  type text
);

-- 3. Future Deliveries Table (Futuras Entregas)
drop table if exists future_deliveries;

create table future_deliveries (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  client_name text not null,
  client_phone text,
  
  product_name text not null,
  quantity integer default 1,
  
  delivery_date timestamp with time zone,
  cod_amount numeric(10,2) default 0,
  notes text
);

-- Enable Row Level Security (RLS)
alter table orders enable row level security;
alter table expenses enable row level security;
alter table future_deliveries enable row level security;

-- Create Policies
create policy "Public Access Orders" on orders for all using (true);
create policy "Public Access Expenses" on expenses for all using (true);
create policy "Public Access Future Deliveries" on future_deliveries for all using (true);
